# These are supported funding model platforms

github: vic3t3chn0 Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: plvice Replace with a single Patreon username
liberapay: pdvicente Replace with a single Liberapay username
